# This file contains the config needed to configure the UI.
# Environment variables will override this config if they exist
# You need to create a config.yml file with your own values to run locally

# This key needs access to the following APIs:
# - Maps JavaScript API
# - Street View API
GOOGLE_API_KEY: "<ENTER_YOUR_GOOGLE_API_KEY_HERE>"

# Please replace the entire value of the ALGOLIA_INDEX_PREFIX setting with your
# GitHub username, including the < and > symbols.
ALGOLIA_INDEX_PREFIX: "<ENTER_YOUR_GITHUB_USERNAME_HERE>"
ALGOLIA_APPLICATION_ID: "<ENTER_YOUR_ALGOLIA_APPLICATION_ID_HERE>"
ALGOLIA_READ_ONLY_API_KEY: "<ENTER_YOUR_ALGOLIA_READ_ONLY_API_KEY_HERE>"

STRAPI_API_TOKEN: ""
STRAPI_API_URL: ""

API_URL: "https://staging.sfserviceguide.org"
API_PROXY_SECURE: true
API_PROXY_CHANGE_ORIGIN: true
API_PROXY_REWRITE: false
